[project]
name = "mayomix"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "httpx2>=2.13.1",
    "pwdlib[argon2]>=0.3.1",
    "pydantic>=2.13.5",
    "pyjwt>=2.14.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.54",
]
[tool.fastapi]
entrypoint = "src.main:app"
[tool.pytest.ini_options]
pythonpath = ["."]
