"""add cached_album

Revision ID: 233e2ae2c89c
Revises: 5c1c78a15caa
Create Date: 2026-10-05 15:16:23.366388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233e2ae2c89c'
down_revision: Union[str, Sequence[str], None] = '5c1c78a15caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_album',
    sa.Column('mbid', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('fetched_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('mbid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_album')
    # ### end Alembic commands ###
