"""add indexes

Revision ID: 5c1c78a15caa
Revises: 0a1f41322147
Create Date: 2026-10-02 15:17:36.874383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1c78a15caa'
down_revision: Union[str, Sequence[str], None] = '0a1f41322147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_connection_user_id1'), 'connection', ['user_id1'], unique=False)
    op.create_index(op.f('ix_connection_user_id2'), 'connection', ['user_id2'], unique=False)
    op.create_index(op.f('ix_review_mbid'), 'review', ['mbid'], unique=False)
    op.create_index(op.f('ix_taste_entry_user_id'), 'taste_entry', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taste_entry_user_id'), table_name='taste_entry')
    op.drop_index(op.f('ix_review_mbid'), table_name='review')
    op.drop_index(op.f('ix_connection_user_id2'), table_name='connection')
    op.drop_index(op.f('ix_connection_user_id1'), table_name='connection')
    # ### end Alembic commands ###
